### ISSUE TITLE
Request: binary distribution / build steps

### ISSUE THREAD

**Issue by vatterspun** [srogatch/TextMatching#1]
Hey I was looking to test this out but as a non-developer, compiling code isn't something I spend a lot of time on.  A friend with some dotnet experience helped me through some of the process but we kept running into minor issues.  I'd love to use the program to compare several text files i have that currently require a lot of manual effort.  Could you post a quick process on how to compile, point to a resource, or post a binary version?

Thanks!

**Comment by srogatch** [comment]
Thanks for your interest in the project. I'll try to post a binary later tonight or tomorrow. Basically, you need to compile the project from Visual Studio 2017 or later, Community edition is fine.

**Comment by vatterspun** [comment]
Awesome, thank you

**Comment by srogatch** [comment]
Could you check the binaries attached to https://github.com/srogatch/TextMatching/releases/tag/v1.1 ?

**Comment by vatterspun** [comment]
I tested out the binaries, works as documented.  I think I may have caught a different issue but I'll close this and create a new issue.  Thanks :)
