### ISSUE TITLE
Bug: Possible difference issue

### ISSUE THREAD

**Issue by vatterspun** [srogatch/TextMatching#2]
**Setup**: Win10x64

**Steps**:

1. Extracted program from the available 64-bit download
1. Launched the program with the available sample files matchtext.exe sample.txt repo and everything works as expected
1. To test out the difference function:
 - I copied the sample.txt exactly as-is to the Repo directory as "Fairy Tales.txt"
 - Another copy was created with one line deleted
 - A 3rd copy was made with two lines deleted

**Result**:

The numberical results were increasing as 0, 1.3, 2.8.  Note that the file output is in the correct order, but the scores seem odd.

![image](https://user-images.githubusercontent.com/1289134/86550648-f6d8b280-bf10-11ea-8a8e-920a465bc465.png)

**Expected result:**

An exact copy should probably have the highest number, followed by the file with one line deleted, and then the file with two lines deleted e.g. 9, 7, 6 or some similar scoring that declines in the series.

**Comment by srogatch** [comment]
Thanks for your inquiry. Please, note `e-05` suffix in the scores for lines 2 and 3. This is the scientific notation for a number: https://www.mathsisfun.com/numbers/scientific-notation.html . It's a way for representing very small numbers, which correspond to very small differences in the texts given on input. So the first number is rather 0.000014... and the second number is rather 0.0000288... That looks correct.

**Comment by vatterspun** [comment]
Understood, thanks for the clarification
